### ISSUE TITLE
Test scripts

### ISSUE THREAD

**Issue by ozkanpakdil** [snowdrop/spring-quarkus-demo1#1]
Hello Georgios 

First of all thanks for the talk in devoxx. Is it possible to add here those scripts for testing. at the end of the video you created some load to present how kubernetes creates new pods. those scripts I am talking about.

Cheers

**Comment by geoand** [comment]
Hi,

Glad you liked it 😊.

The second part of the demo is in this repository: https://github.com/snowdrop/demo-sidebyside

Feel free to take a look and ask me any questions you may have
